export { default as Icon } from "./Icon.png";
export { default as Icon2 } from "./Icon2.png";
export { default as Icon3 } from "./Icon3.png";
export { default as Icon4 } from "./Icon4.png";
export { default as Icon5 } from "./Icon5.png";
export { default as Icon6 } from "./Icon6.png";
export { default as Icon7 } from "./Icon7.png";
export { default as Icon8 } from "./Icon8.png";
export { default as Arrow } from "./Arrow.png";
